### ISSUE TITLE
rails generate chaskiq:install error

### ISSUE THREAD

**Issue by davila7** [michelson/chaskiq-newsletters#11]
When I run "rails generate chaskiq:install"

I get 

rake aborted!
Don't know how to build task 'chaskiq:install:migrations'
/Users/username/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/username/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in`<main>'
(See full trace by running task with --trace)

I have bundle complete.

**Comment by michelson** [comment]
Hola @davila7 , y que tal anda con `railties:install:migrations` ?

saludos

**Comment by davila7** [comment]
@michelson 
rake aborted!
Don't know how to build task 'railties:install:migrations'
aún nada, no se que hago mal

**Comment by michelson** [comment]
¿que version de rails estás usando ?

**Comment by michelson** [comment]
ah , si haces esto `rails generate chaskiq:install` te instala migraciones ?

saludos

**Comment by michelson** [comment]
si nada de eso funciona , puedes copiar las migraciones a mano.

no es lo ideal , pero puedes salir del paso . https://github.com/michelson/chaskiq/tree/master/db/migrate

de todas formas voy a dejar este issue abierto hasta que lo pueda revisar con mas calma

saludos

**Comment by gvidal** [comment]
Hi!

I have the same problem, however, I solved it by indicating the correct github account, because it seems to download another gem that it is called the same as yours (and it is empty)..

Try updating the readme with this:

gem 'chaskiq', git: "https://github.com/michelson/chaskiq"

The problem that now I have with a fresh install of rails 4.2.8 is the following:

> /home/development/.rvm/gems/ruby-2.3.1/bundler/gems/chaskiq-1f0d0e6cf7f1/lib/chaskiq.rb:8:in `require': cannot load such file -- urlcrypt (LoadError)
> 	from /home/development/.rvm/gems/ruby-2.3.1/bundler/gems/chaskiq-1f0d0e6cf7f1/lib/chaskiq.rb:8:in `<top (required)>'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `require'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `each'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `block in require'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `each'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `require'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.5/lib/bundler.rb:107:in `require'
> 	from /home/development/nfs_mount/chaskiq/config/application.rb:7:in `<top (required)>'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/application.rb:82:in `require'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/application.rb:82:in `preload'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
> 	from /home/development/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
> 	from /home/development/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /home/development/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

 
Do you know any idea why this is happening? this gem seems to be correctly installed in my machine

Thank you so much

**Comment by gvidal** [comment]
Ok, I got it, it seems that on lib/chaskiq.rb you have to change the following:

require 'urlcrypt' 

to

require 'URLcrypt'

I'll try to make a pull request when I have time :)
