### ISSUE TITLE
uninitialized constant CarrierWave::Storage::Fog

### ISSUE THREAD

**Issue by gvidal** [michelson/chaskiq-newsletters#12]
Hi there!

I've managed to install your project, however, it displays an error when accessing at CarrierWave:

uninitialized constant CarrierWave::Storage::Fog

Full trace: 

> carrierwave (1.0.0) lib/carrierwave/uploader/configuration.rb:77:in `eval'
> carrierwave (1.0.0) lib/carrierwave/uploader/configuration.rb:77:in `eval'
> carrierwave (1.0.0) lib/carrierwave/uploader/configuration.rb:77:in `storage'
> /home/development/.rvm/gems/ruby-2.3.1/bundler/gems/chaskiq-1f0d0e6cf7f1/app/uploaders/chaskiq/campaign_logo_uploader.rb:11:in `<class:CampaignLogoUploader>'
> /home/development/.rvm/gems/ruby-2.3.1/bundler/gems/chaskiq-1f0d0e6cf7f1/app/uploaders/chaskiq/campaign_logo_uploader.rb:3:in `<module:Chaskiq>'
> /home/development/.rvm/gems/ruby-2.3.1/bundler/gems/chaskiq-1f0d0e6cf7f1/app/uploaders/chaskiq/campaign_logo_uploader.rb:2:in `<top (required)>'
> /home/development/.rvm/gems/ruby-2.3.1/bundler/gems/chaskiq-1f0d0e6cf7f1/app/models/chaskiq/campaign.rb:26:in `<class:Campaign>'
> /home/development/.rvm/gems/ruby-2.3.1/bundler/gems/chaskiq-1f0d0e6cf7f1/app/models/chaskiq/campaign.rb:4:in `<module:Chaskiq>'
> /home/development/.rvm/gems/ruby-2.3.1/bundler/gems/chaskiq-1f0d0e6cf7f1/app/models/chaskiq/campaign.rb:3:in `<top (required)>'
> /home/development/.rvm/gems/ruby-2.3.1/bundler/gems/chaskiq-1f0d0e6cf7f1/app/controllers/chaskiq/dashboard_controller.rb:8:in `show'

Even that I've setted Carrierwave to:

CarrierWave.configure do |config|
  config.storage = :file
  config.root = "#{Rails.root}/tmp"
  config.cache_dir = "#{Rails.root}/tmp/images"
end

Any thoughts?

**Comment by michelson** [comment]
I think I'm using an older version of carrierwave , but I've not declared the version on the gemspec.
can you try to downgrade the carrierwave version to 0.10.0 and see what happens?

**Comment by gvidal** [comment]
Worked!
